// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoFix() {
  return window['go']['main']['App']['AutoFix']();
}

export function CheckStatus() {
  return window['go']['main']['App']['CheckStatus']();
}

export function InstallDriverFile(arg1) {
  return window['go']['main']['App']['InstallDriverFile'](arg1);
}

export function LaunchProcessFile(arg1) {
  return window['go']['main']['App']['LaunchProcessFile'](arg1);
}

export function SelectDriverFile() {
  return window['go']['main']['App']['SelectDriverFile']();
}

export function SelectProcessFile() {
  return window['go']['main']['App']['SelectProcessFile']();
}
