// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AutoFix():Promise<main.ActionResult>;

export function CheckStatus():Promise<main.SystemStatus>;

export function InstallDriverFile(arg1:string):Promise<main.ActionResult>;

export function LaunchProcessFile(arg1:string):Promise<main.ActionResult>;

export function SelectDriverFile():Promise<string>;

export function SelectProcessFile():Promise<string>;
